# For all options see https://github.com/bbatsov/rubocop/tree/master/config

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
  Exclude:
    - .*/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

# Limit lines to 80 characters.
LineLength:
  Max: 90

ClassLength:
  Enabled: false

ModuleLength:
  Enabled: false

# Avoid methods longer than 30 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 87

# Avoid single-line methods.
SingleLineMethods:
  AllowIfMethodIsEmpty: true

StringLiterals:
  Enabled: false

GlobalVars:
  Enabled: false # We use them Redis + StatsD (though maybe we shouldn't?)

# Wants underscores in all large numbers. Pain in the ass for things like
# unix timestamps.
NumericLiterals:
  Enabled: false

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

# Allow non-ASCII characters (e.g. £) in comments
Style/AsciiComments:
  Enabled: false

# Allow method names beginning with capital letters to match Salesforce conventions
Naming/MethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - restforce.gemspec

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile

Lint/UriEscapeUnescape:
  Enabled: false